// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Auth.proto

package via.sep3.protobuf.auth;

public final class AuthOuterClass {
  private AuthOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RegisterUserInput_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RegisterUserInput_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RegisterUserOutput_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RegisterUserOutput_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nAuth.proto\"B\n\021RegisterUserInput\022\014\n\004nam" +
      "e\030\001 \001(\t\022\r\n\005email\030\002 \001(\t\022\020\n\010password\030\003 \001(\t" +
      "\"*\n\022RegisterUserOutput\022\024\n\014isRegistered\030\001" +
      " \001(\0102;\n\004Auth\0223\n\010Register\022\022.RegisterUserI" +
      "nput\032\023.RegisterUserOutputB\032\n\026via.sep3.pr" +
      "otobuf.authP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_RegisterUserInput_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_RegisterUserInput_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RegisterUserInput_descriptor,
        new java.lang.String[] { "Name", "Email", "Password", });
    internal_static_RegisterUserOutput_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_RegisterUserOutput_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RegisterUserOutput_descriptor,
        new java.lang.String[] { "IsRegistered", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
