// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Auth.proto

package via.sep3.protobuf.auth;

public interface RegisterUserOutputOrBuilder extends
    // @@protoc_insertion_point(interface_extends:RegisterUserOutput)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool isRegistered = 1;</code>
   * @return The isRegistered.
   */
  boolean getIsRegistered();
}
