// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Report.proto

package via.sep3.protobuf.report;

public interface ReportListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ReportList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .ReportObject reports = 1;</code>
   */
  java.util.List<via.sep3.protobuf.report.ReportObject> 
      getReportsList();
  /**
   * <code>repeated .ReportObject reports = 1;</code>
   */
  via.sep3.protobuf.report.ReportObject getReports(int index);
  /**
   * <code>repeated .ReportObject reports = 1;</code>
   */
  int getReportsCount();
  /**
   * <code>repeated .ReportObject reports = 1;</code>
   */
  java.util.List<? extends via.sep3.protobuf.report.ReportObjectOrBuilder> 
      getReportsOrBuilderList();
  /**
   * <code>repeated .ReportObject reports = 1;</code>
   */
  via.sep3.protobuf.report.ReportObjectOrBuilder getReportsOrBuilder(
      int index);
}
