// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Report.proto

package via.sep3.protobuf.report;

public final class ReportOuterClass {
  private ReportOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ReportFilter_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ReportFilter_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ReportList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ReportList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ReportObject_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ReportObject_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LocationObject_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LocationObject_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014Report.proto\"\016\n\014ReportFilter\",\n\nReport" +
      "List\022\036\n\007reports\030\001 \003(\0132\r.ReportObject\"\201\001\n" +
      "\014ReportObject\022\014\n\004date\030\001 \001(\t\022\014\n\004time\030\002 \001(" +
      "\t\022\r\n\005proof\030\003 \001(\014\022\023\n\013description\030\004 \001(\t\022\016\n" +
      "\006status\030\005 \001(\t\022!\n\010location\030\006 \001(\0132\017.Locati" +
      "onObject\"C\n\016LocationObject\022\020\n\010latitude\030\001" +
      " \001(\001\022\021\n\tlongitude\030\002 \001(\001\022\014\n\004size\030\003 \001(\00522\n" +
      "\006Report\022(\n\nGetReports\022\r.ReportFilter\032\013.R" +
      "eportListB\034\n\030via.sep3.protobuf.reportP\001b" +
      "\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_ReportFilter_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ReportFilter_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ReportFilter_descriptor,
        new java.lang.String[] { });
    internal_static_ReportList_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ReportList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ReportList_descriptor,
        new java.lang.String[] { "Reports", });
    internal_static_ReportObject_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ReportObject_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ReportObject_descriptor,
        new java.lang.String[] { "Date", "Time", "Proof", "Description", "Status", "Location", });
    internal_static_LocationObject_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_LocationObject_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LocationObject_descriptor,
        new java.lang.String[] { "Latitude", "Longitude", "Size", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
