// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Report.proto

package via.sep3.protobuf.report;

public interface ReportFilterOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ReportFilter)
    com.google.protobuf.MessageOrBuilder {
}
