// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Report.proto

package via.sep3.protobuf.report;

public interface ToReviewReportOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ToReviewReport)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string reportId = 1;</code>
   * @return The reportId.
   */
  java.lang.String getReportId();
  /**
   * <code>string reportId = 1;</code>
   * @return The bytes for reportId.
   */
  com.google.protobuf.ByteString
      getReportIdBytes();

  /**
   * <code>string updatedStatus = 2;</code>
   * @return The updatedStatus.
   */
  java.lang.String getUpdatedStatus();
  /**
   * <code>string updatedStatus = 2;</code>
   * @return The bytes for updatedStatus.
   */
  com.google.protobuf.ByteString
      getUpdatedStatusBytes();
}
