// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Event.proto

package via.sep3.protobuf.event;

public interface ApproveEventFilterOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ApproveEventFilter)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>bool approve = 2;</code>
   * @return The approve.
   */
  boolean getApprove();
}
