// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Event.proto

package via.sep3.protobuf.event;

public interface ApproveEventResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ApproveEventResult)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string confirmation = 1;</code>
   * @return The confirmation.
   */
  java.lang.String getConfirmation();
  /**
   * <code>string confirmation = 1;</code>
   * @return The bytes for confirmation.
   */
  com.google.protobuf.ByteString
      getConfirmationBytes();
}
