// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Event.proto

package via.sep3.protobuf.event;

public interface CreateEventObjectOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CreateEventObject)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string date = 1;</code>
   * @return The date.
   */
  java.lang.String getDate();
  /**
   * <code>string date = 1;</code>
   * @return The bytes for date.
   */
  com.google.protobuf.ByteString
      getDateBytes();

  /**
   * <code>string time = 2;</code>
   * @return The time.
   */
  java.lang.String getTime();
  /**
   * <code>string time = 2;</code>
   * @return The bytes for time.
   */
  com.google.protobuf.ByteString
      getTimeBytes();

  /**
   * <code>string description = 3;</code>
   * @return The description.
   */
  java.lang.String getDescription();
  /**
   * <code>string description = 3;</code>
   * @return The bytes for description.
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();

  /**
   * <code>string status = 4;</code>
   * @return The status.
   */
  java.lang.String getStatus();
  /**
   * <code>string status = 4;</code>
   * @return The bytes for status.
   */
  com.google.protobuf.ByteString
      getStatusBytes();

  /**
   * <code>string creatorEmail = 5;</code>
   * @return The creatorEmail.
   */
  java.lang.String getCreatorEmail();
  /**
   * <code>string creatorEmail = 5;</code>
   * @return The bytes for creatorEmail.
   */
  com.google.protobuf.ByteString
      getCreatorEmailBytes();

  /**
   * <code>string reportId = 6;</code>
   * @return The reportId.
   */
  java.lang.String getReportId();
  /**
   * <code>string reportId = 6;</code>
   * @return The bytes for reportId.
   */
  com.google.protobuf.ByteString
      getReportIdBytes();
}
