// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Event.proto

package via.sep3.protobuf.event;

/**
 * Protobuf type {@code EventObject}
 */
public final class EventObject extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:EventObject)
    EventObjectOrBuilder {
private static final long serialVersionUID = 0L;
  // Use EventObject.newBuilder() to construct.
  private EventObject(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private EventObject() {
    id_ = "";
    date_ = "";
    time_ = "";
    description_ = "";
    status_ = "";
    validation_ = com.google.protobuf.ByteString.EMPTY;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new EventObject();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private EventObject(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            id_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            date_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            time_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            description_ = s;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            status_ = s;
            break;
          }
          case 50: {

            validation_ = input.readBytes();
            break;
          }
          case 58: {
            via.sep3.protobuf.event.UserEventObject.Builder subBuilder = null;
            if (organiser_ != null) {
              subBuilder = organiser_.toBuilder();
            }
            organiser_ = input.readMessage(via.sep3.protobuf.event.UserEventObject.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(organiser_);
              organiser_ = subBuilder.buildPartial();
            }

            break;
          }
          case 66: {
            via.sep3.protobuf.event.ReportEventObject.Builder subBuilder = null;
            if (report_ != null) {
              subBuilder = report_.toBuilder();
            }
            report_ = input.readMessage(via.sep3.protobuf.event.ReportEventObject.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(report_);
              report_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return via.sep3.protobuf.event.EventOuterClass.internal_static_EventObject_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return via.sep3.protobuf.event.EventOuterClass.internal_static_EventObject_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            via.sep3.protobuf.event.EventObject.class, via.sep3.protobuf.event.EventObject.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private volatile java.lang.Object id_;
  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public java.lang.String getId() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      id_ = s;
      return s;
    }
  }
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIdBytes() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      id_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DATE_FIELD_NUMBER = 2;
  private volatile java.lang.Object date_;
  /**
   * <code>string date = 2;</code>
   * @return The date.
   */
  @java.lang.Override
  public java.lang.String getDate() {
    java.lang.Object ref = date_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      date_ = s;
      return s;
    }
  }
  /**
   * <code>string date = 2;</code>
   * @return The bytes for date.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDateBytes() {
    java.lang.Object ref = date_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      date_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TIME_FIELD_NUMBER = 3;
  private volatile java.lang.Object time_;
  /**
   * <code>string time = 3;</code>
   * @return The time.
   */
  @java.lang.Override
  public java.lang.String getTime() {
    java.lang.Object ref = time_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      time_ = s;
      return s;
    }
  }
  /**
   * <code>string time = 3;</code>
   * @return The bytes for time.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTimeBytes() {
    java.lang.Object ref = time_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      time_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DESCRIPTION_FIELD_NUMBER = 4;
  private volatile java.lang.Object description_;
  /**
   * <code>string description = 4;</code>
   * @return The description.
   */
  @java.lang.Override
  public java.lang.String getDescription() {
    java.lang.Object ref = description_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      description_ = s;
      return s;
    }
  }
  /**
   * <code>string description = 4;</code>
   * @return The bytes for description.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDescriptionBytes() {
    java.lang.Object ref = description_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      description_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STATUS_FIELD_NUMBER = 5;
  private volatile java.lang.Object status_;
  /**
   * <code>string status = 5;</code>
   * @return The status.
   */
  @java.lang.Override
  public java.lang.String getStatus() {
    java.lang.Object ref = status_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      status_ = s;
      return s;
    }
  }
  /**
   * <code>string status = 5;</code>
   * @return The bytes for status.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getStatusBytes() {
    java.lang.Object ref = status_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      status_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int VALIDATION_FIELD_NUMBER = 6;
  private com.google.protobuf.ByteString validation_;
  /**
   * <code>bytes validation = 6;</code>
   * @return The validation.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getValidation() {
    return validation_;
  }

  public static final int ORGANISER_FIELD_NUMBER = 7;
  private via.sep3.protobuf.event.UserEventObject organiser_;
  /**
   * <code>.UserEventObject organiser = 7;</code>
   * @return Whether the organiser field is set.
   */
  @java.lang.Override
  public boolean hasOrganiser() {
    return organiser_ != null;
  }
  /**
   * <code>.UserEventObject organiser = 7;</code>
   * @return The organiser.
   */
  @java.lang.Override
  public via.sep3.protobuf.event.UserEventObject getOrganiser() {
    return organiser_ == null ? via.sep3.protobuf.event.UserEventObject.getDefaultInstance() : organiser_;
  }
  /**
   * <code>.UserEventObject organiser = 7;</code>
   */
  @java.lang.Override
  public via.sep3.protobuf.event.UserEventObjectOrBuilder getOrganiserOrBuilder() {
    return getOrganiser();
  }

  public static final int REPORT_FIELD_NUMBER = 8;
  private via.sep3.protobuf.event.ReportEventObject report_;
  /**
   * <code>.ReportEventObject report = 8;</code>
   * @return Whether the report field is set.
   */
  @java.lang.Override
  public boolean hasReport() {
    return report_ != null;
  }
  /**
   * <code>.ReportEventObject report = 8;</code>
   * @return The report.
   */
  @java.lang.Override
  public via.sep3.protobuf.event.ReportEventObject getReport() {
    return report_ == null ? via.sep3.protobuf.event.ReportEventObject.getDefaultInstance() : report_;
  }
  /**
   * <code>.ReportEventObject report = 8;</code>
   */
  @java.lang.Override
  public via.sep3.protobuf.event.ReportEventObjectOrBuilder getReportOrBuilder() {
    return getReport();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(id_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(date_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, date_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(time_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, time_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(description_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, description_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(status_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, status_);
    }
    if (!validation_.isEmpty()) {
      output.writeBytes(6, validation_);
    }
    if (organiser_ != null) {
      output.writeMessage(7, getOrganiser());
    }
    if (report_ != null) {
      output.writeMessage(8, getReport());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(id_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(date_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, date_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(time_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, time_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(description_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, description_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(status_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, status_);
    }
    if (!validation_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(6, validation_);
    }
    if (organiser_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, getOrganiser());
    }
    if (report_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(8, getReport());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof via.sep3.protobuf.event.EventObject)) {
      return super.equals(obj);
    }
    via.sep3.protobuf.event.EventObject other = (via.sep3.protobuf.event.EventObject) obj;

    if (!getId()
        .equals(other.getId())) return false;
    if (!getDate()
        .equals(other.getDate())) return false;
    if (!getTime()
        .equals(other.getTime())) return false;
    if (!getDescription()
        .equals(other.getDescription())) return false;
    if (!getStatus()
        .equals(other.getStatus())) return false;
    if (!getValidation()
        .equals(other.getValidation())) return false;
    if (hasOrganiser() != other.hasOrganiser()) return false;
    if (hasOrganiser()) {
      if (!getOrganiser()
          .equals(other.getOrganiser())) return false;
    }
    if (hasReport() != other.hasReport()) return false;
    if (hasReport()) {
      if (!getReport()
          .equals(other.getReport())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId().hashCode();
    hash = (37 * hash) + DATE_FIELD_NUMBER;
    hash = (53 * hash) + getDate().hashCode();
    hash = (37 * hash) + TIME_FIELD_NUMBER;
    hash = (53 * hash) + getTime().hashCode();
    hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
    hash = (53 * hash) + getDescription().hashCode();
    hash = (37 * hash) + STATUS_FIELD_NUMBER;
    hash = (53 * hash) + getStatus().hashCode();
    hash = (37 * hash) + VALIDATION_FIELD_NUMBER;
    hash = (53 * hash) + getValidation().hashCode();
    if (hasOrganiser()) {
      hash = (37 * hash) + ORGANISER_FIELD_NUMBER;
      hash = (53 * hash) + getOrganiser().hashCode();
    }
    if (hasReport()) {
      hash = (37 * hash) + REPORT_FIELD_NUMBER;
      hash = (53 * hash) + getReport().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static via.sep3.protobuf.event.EventObject parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static via.sep3.protobuf.event.EventObject parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static via.sep3.protobuf.event.EventObject parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static via.sep3.protobuf.event.EventObject parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static via.sep3.protobuf.event.EventObject parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static via.sep3.protobuf.event.EventObject parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static via.sep3.protobuf.event.EventObject parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static via.sep3.protobuf.event.EventObject parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static via.sep3.protobuf.event.EventObject parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static via.sep3.protobuf.event.EventObject parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static via.sep3.protobuf.event.EventObject parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static via.sep3.protobuf.event.EventObject parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(via.sep3.protobuf.event.EventObject prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code EventObject}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:EventObject)
      via.sep3.protobuf.event.EventObjectOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return via.sep3.protobuf.event.EventOuterClass.internal_static_EventObject_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return via.sep3.protobuf.event.EventOuterClass.internal_static_EventObject_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              via.sep3.protobuf.event.EventObject.class, via.sep3.protobuf.event.EventObject.Builder.class);
    }

    // Construct using via.sep3.protobuf.event.EventObject.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      id_ = "";

      date_ = "";

      time_ = "";

      description_ = "";

      status_ = "";

      validation_ = com.google.protobuf.ByteString.EMPTY;

      if (organiserBuilder_ == null) {
        organiser_ = null;
      } else {
        organiser_ = null;
        organiserBuilder_ = null;
      }
      if (reportBuilder_ == null) {
        report_ = null;
      } else {
        report_ = null;
        reportBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return via.sep3.protobuf.event.EventOuterClass.internal_static_EventObject_descriptor;
    }

    @java.lang.Override
    public via.sep3.protobuf.event.EventObject getDefaultInstanceForType() {
      return via.sep3.protobuf.event.EventObject.getDefaultInstance();
    }

    @java.lang.Override
    public via.sep3.protobuf.event.EventObject build() {
      via.sep3.protobuf.event.EventObject result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public via.sep3.protobuf.event.EventObject buildPartial() {
      via.sep3.protobuf.event.EventObject result = new via.sep3.protobuf.event.EventObject(this);
      result.id_ = id_;
      result.date_ = date_;
      result.time_ = time_;
      result.description_ = description_;
      result.status_ = status_;
      result.validation_ = validation_;
      if (organiserBuilder_ == null) {
        result.organiser_ = organiser_;
      } else {
        result.organiser_ = organiserBuilder_.build();
      }
      if (reportBuilder_ == null) {
        result.report_ = report_;
      } else {
        result.report_ = reportBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof via.sep3.protobuf.event.EventObject) {
        return mergeFrom((via.sep3.protobuf.event.EventObject)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(via.sep3.protobuf.event.EventObject other) {
      if (other == via.sep3.protobuf.event.EventObject.getDefaultInstance()) return this;
      if (!other.getId().isEmpty()) {
        id_ = other.id_;
        onChanged();
      }
      if (!other.getDate().isEmpty()) {
        date_ = other.date_;
        onChanged();
      }
      if (!other.getTime().isEmpty()) {
        time_ = other.time_;
        onChanged();
      }
      if (!other.getDescription().isEmpty()) {
        description_ = other.description_;
        onChanged();
      }
      if (!other.getStatus().isEmpty()) {
        status_ = other.status_;
        onChanged();
      }
      if (other.getValidation() != com.google.protobuf.ByteString.EMPTY) {
        setValidation(other.getValidation());
      }
      if (other.hasOrganiser()) {
        mergeOrganiser(other.getOrganiser());
      }
      if (other.hasReport()) {
        mergeReport(other.getReport());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      via.sep3.protobuf.event.EventObject parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (via.sep3.protobuf.event.EventObject) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object id_ = "";
    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      
      id_ = getDefaultInstance().getId();
      onChanged();
      return this;
    }
    /**
     * <code>string id = 1;</code>
     * @param value The bytes for id to set.
     * @return This builder for chaining.
     */
    public Builder setIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      id_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object date_ = "";
    /**
     * <code>string date = 2;</code>
     * @return The date.
     */
    public java.lang.String getDate() {
      java.lang.Object ref = date_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        date_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string date = 2;</code>
     * @return The bytes for date.
     */
    public com.google.protobuf.ByteString
        getDateBytes() {
      java.lang.Object ref = date_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        date_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string date = 2;</code>
     * @param value The date to set.
     * @return This builder for chaining.
     */
    public Builder setDate(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      date_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string date = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearDate() {
      
      date_ = getDefaultInstance().getDate();
      onChanged();
      return this;
    }
    /**
     * <code>string date = 2;</code>
     * @param value The bytes for date to set.
     * @return This builder for chaining.
     */
    public Builder setDateBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      date_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object time_ = "";
    /**
     * <code>string time = 3;</code>
     * @return The time.
     */
    public java.lang.String getTime() {
      java.lang.Object ref = time_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        time_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string time = 3;</code>
     * @return The bytes for time.
     */
    public com.google.protobuf.ByteString
        getTimeBytes() {
      java.lang.Object ref = time_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        time_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string time = 3;</code>
     * @param value The time to set.
     * @return This builder for chaining.
     */
    public Builder setTime(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      time_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string time = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearTime() {
      
      time_ = getDefaultInstance().getTime();
      onChanged();
      return this;
    }
    /**
     * <code>string time = 3;</code>
     * @param value The bytes for time to set.
     * @return This builder for chaining.
     */
    public Builder setTimeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      time_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object description_ = "";
    /**
     * <code>string description = 4;</code>
     * @return The description.
     */
    public java.lang.String getDescription() {
      java.lang.Object ref = description_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        description_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string description = 4;</code>
     * @return The bytes for description.
     */
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string description = 4;</code>
     * @param value The description to set.
     * @return This builder for chaining.
     */
    public Builder setDescription(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      description_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string description = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearDescription() {
      
      description_ = getDefaultInstance().getDescription();
      onChanged();
      return this;
    }
    /**
     * <code>string description = 4;</code>
     * @param value The bytes for description to set.
     * @return This builder for chaining.
     */
    public Builder setDescriptionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      description_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object status_ = "";
    /**
     * <code>string status = 5;</code>
     * @return The status.
     */
    public java.lang.String getStatus() {
      java.lang.Object ref = status_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        status_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string status = 5;</code>
     * @return The bytes for status.
     */
    public com.google.protobuf.ByteString
        getStatusBytes() {
      java.lang.Object ref = status_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        status_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string status = 5;</code>
     * @param value The status to set.
     * @return This builder for chaining.
     */
    public Builder setStatus(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      status_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string status = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearStatus() {
      
      status_ = getDefaultInstance().getStatus();
      onChanged();
      return this;
    }
    /**
     * <code>string status = 5;</code>
     * @param value The bytes for status to set.
     * @return This builder for chaining.
     */
    public Builder setStatusBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      status_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString validation_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes validation = 6;</code>
     * @return The validation.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getValidation() {
      return validation_;
    }
    /**
     * <code>bytes validation = 6;</code>
     * @param value The validation to set.
     * @return This builder for chaining.
     */
    public Builder setValidation(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      validation_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bytes validation = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearValidation() {
      
      validation_ = getDefaultInstance().getValidation();
      onChanged();
      return this;
    }

    private via.sep3.protobuf.event.UserEventObject organiser_;
    private com.google.protobuf.SingleFieldBuilderV3<
        via.sep3.protobuf.event.UserEventObject, via.sep3.protobuf.event.UserEventObject.Builder, via.sep3.protobuf.event.UserEventObjectOrBuilder> organiserBuilder_;
    /**
     * <code>.UserEventObject organiser = 7;</code>
     * @return Whether the organiser field is set.
     */
    public boolean hasOrganiser() {
      return organiserBuilder_ != null || organiser_ != null;
    }
    /**
     * <code>.UserEventObject organiser = 7;</code>
     * @return The organiser.
     */
    public via.sep3.protobuf.event.UserEventObject getOrganiser() {
      if (organiserBuilder_ == null) {
        return organiser_ == null ? via.sep3.protobuf.event.UserEventObject.getDefaultInstance() : organiser_;
      } else {
        return organiserBuilder_.getMessage();
      }
    }
    /**
     * <code>.UserEventObject organiser = 7;</code>
     */
    public Builder setOrganiser(via.sep3.protobuf.event.UserEventObject value) {
      if (organiserBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        organiser_ = value;
        onChanged();
      } else {
        organiserBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.UserEventObject organiser = 7;</code>
     */
    public Builder setOrganiser(
        via.sep3.protobuf.event.UserEventObject.Builder builderForValue) {
      if (organiserBuilder_ == null) {
        organiser_ = builderForValue.build();
        onChanged();
      } else {
        organiserBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.UserEventObject organiser = 7;</code>
     */
    public Builder mergeOrganiser(via.sep3.protobuf.event.UserEventObject value) {
      if (organiserBuilder_ == null) {
        if (organiser_ != null) {
          organiser_ =
            via.sep3.protobuf.event.UserEventObject.newBuilder(organiser_).mergeFrom(value).buildPartial();
        } else {
          organiser_ = value;
        }
        onChanged();
      } else {
        organiserBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.UserEventObject organiser = 7;</code>
     */
    public Builder clearOrganiser() {
      if (organiserBuilder_ == null) {
        organiser_ = null;
        onChanged();
      } else {
        organiser_ = null;
        organiserBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.UserEventObject organiser = 7;</code>
     */
    public via.sep3.protobuf.event.UserEventObject.Builder getOrganiserBuilder() {
      
      onChanged();
      return getOrganiserFieldBuilder().getBuilder();
    }
    /**
     * <code>.UserEventObject organiser = 7;</code>
     */
    public via.sep3.protobuf.event.UserEventObjectOrBuilder getOrganiserOrBuilder() {
      if (organiserBuilder_ != null) {
        return organiserBuilder_.getMessageOrBuilder();
      } else {
        return organiser_ == null ?
            via.sep3.protobuf.event.UserEventObject.getDefaultInstance() : organiser_;
      }
    }
    /**
     * <code>.UserEventObject organiser = 7;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        via.sep3.protobuf.event.UserEventObject, via.sep3.protobuf.event.UserEventObject.Builder, via.sep3.protobuf.event.UserEventObjectOrBuilder> 
        getOrganiserFieldBuilder() {
      if (organiserBuilder_ == null) {
        organiserBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            via.sep3.protobuf.event.UserEventObject, via.sep3.protobuf.event.UserEventObject.Builder, via.sep3.protobuf.event.UserEventObjectOrBuilder>(
                getOrganiser(),
                getParentForChildren(),
                isClean());
        organiser_ = null;
      }
      return organiserBuilder_;
    }

    private via.sep3.protobuf.event.ReportEventObject report_;
    private com.google.protobuf.SingleFieldBuilderV3<
        via.sep3.protobuf.event.ReportEventObject, via.sep3.protobuf.event.ReportEventObject.Builder, via.sep3.protobuf.event.ReportEventObjectOrBuilder> reportBuilder_;
    /**
     * <code>.ReportEventObject report = 8;</code>
     * @return Whether the report field is set.
     */
    public boolean hasReport() {
      return reportBuilder_ != null || report_ != null;
    }
    /**
     * <code>.ReportEventObject report = 8;</code>
     * @return The report.
     */
    public via.sep3.protobuf.event.ReportEventObject getReport() {
      if (reportBuilder_ == null) {
        return report_ == null ? via.sep3.protobuf.event.ReportEventObject.getDefaultInstance() : report_;
      } else {
        return reportBuilder_.getMessage();
      }
    }
    /**
     * <code>.ReportEventObject report = 8;</code>
     */
    public Builder setReport(via.sep3.protobuf.event.ReportEventObject value) {
      if (reportBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        report_ = value;
        onChanged();
      } else {
        reportBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.ReportEventObject report = 8;</code>
     */
    public Builder setReport(
        via.sep3.protobuf.event.ReportEventObject.Builder builderForValue) {
      if (reportBuilder_ == null) {
        report_ = builderForValue.build();
        onChanged();
      } else {
        reportBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.ReportEventObject report = 8;</code>
     */
    public Builder mergeReport(via.sep3.protobuf.event.ReportEventObject value) {
      if (reportBuilder_ == null) {
        if (report_ != null) {
          report_ =
            via.sep3.protobuf.event.ReportEventObject.newBuilder(report_).mergeFrom(value).buildPartial();
        } else {
          report_ = value;
        }
        onChanged();
      } else {
        reportBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.ReportEventObject report = 8;</code>
     */
    public Builder clearReport() {
      if (reportBuilder_ == null) {
        report_ = null;
        onChanged();
      } else {
        report_ = null;
        reportBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.ReportEventObject report = 8;</code>
     */
    public via.sep3.protobuf.event.ReportEventObject.Builder getReportBuilder() {
      
      onChanged();
      return getReportFieldBuilder().getBuilder();
    }
    /**
     * <code>.ReportEventObject report = 8;</code>
     */
    public via.sep3.protobuf.event.ReportEventObjectOrBuilder getReportOrBuilder() {
      if (reportBuilder_ != null) {
        return reportBuilder_.getMessageOrBuilder();
      } else {
        return report_ == null ?
            via.sep3.protobuf.event.ReportEventObject.getDefaultInstance() : report_;
      }
    }
    /**
     * <code>.ReportEventObject report = 8;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        via.sep3.protobuf.event.ReportEventObject, via.sep3.protobuf.event.ReportEventObject.Builder, via.sep3.protobuf.event.ReportEventObjectOrBuilder> 
        getReportFieldBuilder() {
      if (reportBuilder_ == null) {
        reportBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            via.sep3.protobuf.event.ReportEventObject, via.sep3.protobuf.event.ReportEventObject.Builder, via.sep3.protobuf.event.ReportEventObjectOrBuilder>(
                getReport(),
                getParentForChildren(),
                isClean());
        report_ = null;
      }
      return reportBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:EventObject)
  }

  // @@protoc_insertion_point(class_scope:EventObject)
  private static final via.sep3.protobuf.event.EventObject DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new via.sep3.protobuf.event.EventObject();
  }

  public static via.sep3.protobuf.event.EventObject getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<EventObject>
      PARSER = new com.google.protobuf.AbstractParser<EventObject>() {
    @java.lang.Override
    public EventObject parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new EventObject(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<EventObject> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<EventObject> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public via.sep3.protobuf.event.EventObject getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

