// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Event.proto

package via.sep3.protobuf.event;

public interface EventFilterOrBuilder extends
    // @@protoc_insertion_point(interface_extends:EventFilter)
    com.google.protobuf.MessageOrBuilder {
}
