// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Event.proto

package via.sep3.protobuf.event;

public interface EventListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:EventList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .EventObject events = 1;</code>
   */
  java.util.List<via.sep3.protobuf.event.EventObject> 
      getEventsList();
  /**
   * <code>repeated .EventObject events = 1;</code>
   */
  via.sep3.protobuf.event.EventObject getEvents(int index);
  /**
   * <code>repeated .EventObject events = 1;</code>
   */
  int getEventsCount();
  /**
   * <code>repeated .EventObject events = 1;</code>
   */
  java.util.List<? extends via.sep3.protobuf.event.EventObjectOrBuilder> 
      getEventsOrBuilderList();
  /**
   * <code>repeated .EventObject events = 1;</code>
   */
  via.sep3.protobuf.event.EventObjectOrBuilder getEventsOrBuilder(
      int index);
}
