// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Event.proto

package via.sep3.protobuf.event;

public interface EventsFilterOrBuilder extends
    // @@protoc_insertion_point(interface_extends:EventsFilter)
    com.google.protobuf.MessageOrBuilder {
}
