// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Event.proto

package via.sep3.protobuf.event;

public interface LocationEventObjectOrBuilder extends
    // @@protoc_insertion_point(interface_extends:LocationEventObject)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double longitude = 1;</code>
   * @return The longitude.
   */
  double getLongitude();

  /**
   * <code>double latitude = 2;</code>
   * @return The latitude.
   */
  double getLatitude();

  /**
   * <code>int32 size = 3;</code>
   * @return The size.
   */
  int getSize();
}
