// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Event.proto

package via.sep3.protobuf.event;

public interface ReportEventObjectOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ReportEventObject)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional bytes proof = 1;</code>
   * @return Whether the proof field is set.
   */
  boolean hasProof();
  /**
   * <code>optional bytes proof = 1;</code>
   * @return The proof.
   */
  com.google.protobuf.ByteString getProof();

  /**
   * <code>string description = 2;</code>
   * @return The description.
   */
  java.lang.String getDescription();
  /**
   * <code>string description = 2;</code>
   * @return The bytes for description.
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();

  /**
   * <code>.LocationEventObject location = 3;</code>
   * @return Whether the location field is set.
   */
  boolean hasLocation();
  /**
   * <code>.LocationEventObject location = 3;</code>
   * @return The location.
   */
  via.sep3.protobuf.event.LocationEventObject getLocation();
  /**
   * <code>.LocationEventObject location = 3;</code>
   */
  via.sep3.protobuf.event.LocationEventObjectOrBuilder getLocationOrBuilder();
}
