// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Event.proto

package via.sep3.protobuf.event;

public interface ReportObjectOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ReportObject)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes proof = 1;</code>
   * @return The proof.
   */
  com.google.protobuf.ByteString getProof();

  /**
   * <code>string description = 2;</code>
   * @return The description.
   */
  java.lang.String getDescription();
  /**
   * <code>string description = 2;</code>
   * @return The bytes for description.
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();

  /**
   * <code>.LocationObject location = 3;</code>
   * @return Whether the location field is set.
   */
  boolean hasLocation();
  /**
   * <code>.LocationObject location = 3;</code>
   * @return The location.
   */
  via.sep3.protobuf.event.LocationObject getLocation();
  /**
   * <code>.LocationObject location = 3;</code>
   */
  via.sep3.protobuf.event.LocationObjectOrBuilder getLocationOrBuilder();
}
