// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Event.proto

package via.sep3.protobuf.event;

public interface ValidationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Validation)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string eventId = 1;</code>
   * @return The eventId.
   */
  java.lang.String getEventId();
  /**
   * <code>string eventId = 1;</code>
   * @return The bytes for eventId.
   */
  com.google.protobuf.ByteString
      getEventIdBytes();

  /**
   * <code>bytes validation = 2;</code>
   * @return The validation.
   */
  com.google.protobuf.ByteString getValidation();
}
